import { Data } from "@/context/context";
import { Ubuntu } from "next/font/google";
import Head from "../pageComponents/header";
import Footer from "../pageComponents/footer";
// import { AuthContextProvider } from "@/context/userContext";
import "./globals.css";
import { Suspense } from "react";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Locco Biz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${ubuntu.className} antialiased`}>
        <Suspense fallback={<div>Loading...</div>}>
          <Data>
            <Head />
            <div className="min-h-screen">{children}</div>
            <Footer />
          </Data>
        </Suspense>
      </body>
    </html>
  );
}
